[versions]
edc = "0.14.1"
edc-build = "1.1.2"
shadow = "8.1.1"
junit = "5.13.4"
assertj = "3.27.0"
mockito = "5.14.2"

[libraries]
# upstream EDC dependencies
edc-boot = { module = "org.eclipse.edc:boot", version.ref = "edc" }
edc-config-fs = { module = "org.eclipse.edc:configuration-filesystem", version.ref = "edc" }
edc-did-core = { module = "org.eclipse.edc:identity-did-core", version.ref = "edc" }
edc-did-web = { module = "org.eclipse.edc:identity-did-web", version.ref = "edc" }
edc-core-api = { module = "org.eclipse.edc:api-core", version.ref = "edc" }
edc-core-runtime = { module = "org.eclipse.edc:runtime-core", version.ref = "edc" }
edc-ext-http = { module = "org.eclipse.edc:http", version.ref = "edc" }
edc-ext-jsonld = { module = "org.eclipse.edc:json-ld", version.ref = "edc" }

# identityhub SPI modules
edc-ih-spi = { module = "org.eclipse.edc:identity-hub-spi", version.ref = "edc" }
edc-ih-spi-credentials = { module = "org.eclipse.edc:verifiable-credential-spi", version.ref = "edc" }
edc-ih-spi-did = { module = "org.eclipse.edc:did-spi", version.ref = "edc" }

# identityhub API modules
edc-ih-api-did = { module = "org.eclipse.edc:did-api", version.ref = "edc" }
edc-ih-api-participants = { module = "org.eclipse.edc:participant-context-api", version.ref = "edc" }

# EDC lib dependencies
edc-lib-crypto = { module = "org.eclipse.edc:crypto-common-lib", version.ref = "edc" }
edc-lib-keys = { module = "org.eclipse.edc:keys-lib", version.ref = "edc" }

# EDC SPI modules
edc-spi-identity-did = { module = "org.eclipse.edc:identity-did-spi", version.ref = "edc" }

# Test dependencies
edc-junit = { module = "org.eclipse.edc:junit", version.ref = "edc" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }

# BOM modules
edc-bom-identityhub = { module = "org.eclipse.edc:identityhub-bom", version.ref = "edc" }
edc-bom-identityhub-sql = { module = "org.eclipse.edc:identityhub-feature-sql-bom", version.ref = "edc" }

# vault
edc-vault-hashicorp = { module = "org.eclipse.edc:vault-hashicorp", version.ref = "edc" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
edc-build = { id = "org.eclipse.edc.edc-build", version.ref = "edc-build" }
